config/routes.rb
Rails.application.routes.draw do
  #devise_for :customers

  root to: 'public/homes#top'
  scope module: :public do
    get "/about" => "homes#about" , as: "about"
    resources :items, only: [:index, :show, :create]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post :confirm
        get :compleate
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    devise_for :customers, :controllers => {
    :registrations => 'public/registrations',
    :sessions => 'public/sessions',
    :passwords => 'public/passwords'
   }
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:show, :edit, :update]
  end



  namespace :admin do
    root to: 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
  end

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  validates :amount, presence: true
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_ditails
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_ditails, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  validates :payment_method, presence: true
  validates :address, presence: true
end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
    @genre = Genre.all

  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_items_path
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @order = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_ditail = OrderDitail.find_by(order_id: params[:id])
    @order_ditails = Order.find(params[:id]).order_ditails.all
    @shipping = 800
    @total_price = 0
    @payment = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_orders_path
    else
        root_path
    end
end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/items/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>画像編集</h2>
      <%= form_with model: @item, url:"/admin/items/#{@item.id}", local:true do |f| %>
      <div>
        <p>商品画像</p>
        <p><%= f.attachment_field :image %></p>
      </div>
      <div>
        <p>商品名</p>
        <p><%= f.text_field :name %></p>
      </div>
      <div>
        <p>商品説明</p>
        <p><%= f.text_area :introduction %></p>
      </div>
      <div>
        <p>ジャンル</p>
        <p><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %></p>
      </div>
      <div>
        <p>税抜価格</p>
        <p><%= f.text_field :price %></p>
      </div>
      <%= f.submit '変更を保存', class:'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="col-md-8 offset-md-1">
  <h4>商品一覧</h4>
  <table>
    <thead>
      <th width="80" heigth="24">商品ID</th>
      <th width="300" heigth="24">商品名</th>
      <th width="200" heigth="24">税抜価格</th>
      <th width="300" heigth="24">ジャンル</th>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td>
          <%= link_to admin_item_path(item.id) do %>
            <%= item.name %>
          <% end %>
        </td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to '新規登録画面に進む', new_admin_item_path, class:'btn btn-primary' %>
</div>

app/views/admin/items/new.html.erb
<p id="notice"></p>
<div class="col-md-8 offset-md-1">
  <h4>商品新規登録</h4>
  <%= form_with model:@item, url: admin_items_path, local:true do |f| %>
    <p>商品画像</p>
    <%= f.attachment_field :image %>
    <p>商品名</p>
    <%= f.text_field :name %>
    <p>商品説明</p>
    <%= f.text_area :introduction %>
    <p>ジャンル</p>
    <%= f.collection_select :genre_id, @genre.all, :id, :name, include_blank: "選択して下さい" %>
    <p>税抜き価格</p>
    <%= f.text_field :price %>円
    <%= f.submit '新規登録', class:'btn btn-success' %>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<p id="notice"></p>
<h4>商品詳細</h4>
  <div class="container px-5 px-sm-0">
  　<div class="row">
    　<div class="col-md-3">
      　<%= attachment_image_tag @item, :image, :fill, 200, 200, format: 'jpeg' %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h6>商品名</h6>
        <p><%= @item.name %></p>
        <h6>商品説明</h6>
        <p><%= @item.introduction %></p>
        <h6>ジャンル</h6>
        <p><%= @item.genre_id %></p>
        <h6>税抜価格</h6>
        <p><%= @item.price %>円</p>
        <%= link_to '編集する', edit_admin_item_path(@item.id), class:'btn btn-sm btn-success' %>
      </div>
    </div>
  </div>

app/views/admin/orders/index.html.erb
<div class="col-md-8 offset-md-1">
  <h4>注文履歴一覧</h4>
  <table>
    <thead>
      <th width="100" heigth="24">購入日時</th>
      <th width="300" heigth="24">購入者</th>
      <th width="200" heigth="24">注文個数</th>
    </thead>
    <tbody>
      <% @order.each do |order| %>
      <% @amount = 0 %>
      <tr>
        <td>
          <%= link_to admin_order_path(order.id) do %>
            <%= order.created_at.strftime('%Y/%m/%d') %>
          <% end %>
        </td>
        <td><%= order.name %></td>
        <% order.order_ditails.each do |order_ditail| %>
          <% @amount += (order_ditail.amount) %>
      　<% end %>
        <td><%= @amount %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<h4>注文履歴詳細</h4>
  <div class="container px-5 px-sm-0">
  　<div class="row">
      <div class="col-md-8 offset-md-1">
        <h6>購入者</h6>
        <p><%= @order.name %></p>
        <h6>注文日</h6>
        <p><%= @order.created_at.strftime('%Y/%m/%d') %></p>
        <h6>配送先</h6>
        <p><%= @order.address %></p>
        <h6>支払い方法</h6>
        <p><%= @order.payment_method_i18n %></p>
        <table>
          <thead>
            <th width="300" heigth="24">商品</th>
            <th width="100" heigth="24">単価（税込）</th>
            <th width="100" heigth="24">数量</th>
            <th width="100" heigth="24">小計</th>
          </thead>
        <tbody>
        <% @order_ditails.each do |a| %>
        <% @subtotal = 0 %>
          <tr>
            <td><%= a.item.name %></td>
            <td><%= a.item.with_tax_price %></td>
            <td><%= a.amount %></td>
            <td>
              <% @subtotal += ((a.item.price * 1.1).floor) * (a.amount) %>
              <%= @subtotal %>
            </td>
          </tr>
        <% @total_price += @subtotal %>
        <% end %>
        </tbody>
        <h5>請求情報</h5>
        <% @payment += @shipping + @total_price %>
        <table>
          <thead>
            <th>商品合計</th>
            <th><%= @total_price %>円</th>
          </thead>
          <thead>
            <th>配送料</th>
            <th><%= @shipping %>円</th>
          </thead>
          <thead>
            <th>ご請求額</th>
            <th><%= @payment %></th>
          </thead>
        </table>
      </div>
    </div>
  </div>