config/routes.rb
Rails.application.routes.draw do
  #devise_for :customers

  root to: 'public/homes#top'
  scope module: :public do
    get "/about" => "homes#about" , as: "about"
    resources :items, only: [:index, :show, :create]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post :confirm
        get :compleate
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    devise_for :customers, :controllers => {
    :registrations => 'public/registrations',
    :sessions => 'public/sessions',
    :passwords => 'public/passwords'
   }
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:show, :edit, :update]
  end



  namespace :admin do
    root to: 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
  end

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  validates :amount, presence: true
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_ditails
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_ditails, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  validates :payment_method, presence: true
  validates :address, presence: true
end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_orders_path
    else
        root_path
    end
end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg border-bottom border-dark">
        <div class="container">
          <span><%= link_to "LOGO", root_path, class:"navbar-brand border border-dark text-dark" %></span>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <li>
              <%= link_to 'マイページ', customer_path(current_customer.id), class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to '商品一覧', items_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to 'カート', cart_items_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <% elsif admin_signed_in? then %>
            <li>
              <%= link_to '商品一覧', admin_items_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to '会員一覧', admin_customers_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to '注文履歴一覧', admin_orders_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to 'ジャンル一覧', admin_genres_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <% else %>
            <li>
              <%= link_to 'About', about_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to '商品一覧', items_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <li>
              <%= link_to "ログイン", new_customer_session_path, class:"btn btn-light border rounded-lg border-secondary text-dark" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>
    <footer class="border-top border-dark">
  </body>
</html>